export function ToolsPanel({ quiz, quizAnswer, setQuizAnswer, quizMessage, setQuizMessage, startQuiz, converter, setConverter, unitDefinitions, convertValue }) {
  const units = Object.keys(unitDefinitions)
  const sameGroupUnits = units.filter((unit) => unitDefinitions[unit].group === unitDefinitions[converter.from].group)
  return <section className="tools-section" id="tools"><div className="tool-card"><div><span className="section-kicker">Quick challenge</span><h2>Test your knowledge</h2><p>Get a random formula and enter the correct answer.</p></div><button className="tool-button" onClick={startQuiz}>Start quick quiz</button>{quiz && <div className="quiz-box"><strong>{quiz.formula.name}</strong><span>{quiz.formula.symbol}</span><small>Use these values: {quiz.formula.variables.map((v, index) => `${v.label} = ${index + 2}`).join(', ')}</small><div className="quiz-input"><input type="number" value={quizAnswer} onChange={(event) => setQuizAnswer(event.target.value)} placeholder="Your answer" /><button onClick={() => setQuizMessage(Math.abs(Number(quizAnswer) - quiz.answer) < 0.05 ? 'Correct! Great work.' : `Not quite — the answer is ${Number(quiz.answer).toFixed(2)}.`)}>Check</button></div><b className={quizMessage.startsWith('Correct') ? 'success-message' : 'error-message'}>{quizMessage}</b></div>}</div><div className="tool-card converter-card"><div><span className="section-kicker">Unit converter</span><h2>Convert units</h2><p>Switch between length, mass, time, temperature, and pressure units.</p></div><div className="converter-row"><input type="number" value={converter.amount} onChange={(event) => setConverter({ ...converter, amount: event.target.value })} placeholder="Amount" /><select value={converter.from} onChange={(event) => { const from = event.target.value; const options = units.filter((unit) => unitDefinitions[unit].group === unitDefinitions[from].group); setConverter({ ...converter, from, to: options.find((unit) => unit !== from) || from }) }}>{units.map((unit) => <option key={unit} value={unit}>{unit}</option>)}</select><span>→</span><select value={converter.to} onChange={(event) => setConverter({ ...converter, to: event.target.value })}>{sameGroupUnits.map((unit) => <option key={unit} value={unit}>{unit}</option>)}</select><strong>{convertValue === '' ? '—' : Number(convertValue).toFixed(4)}</strong></div></div></section>
}

export function HistoryPanel({ history, showHistory, onClear }) {
  if (!showHistory) return null
  return <section className="history-panel"><div className="section-heading"><div><span className="section-kicker">Your activity</span><h2>Calculation history</h2></div><button className="clear-history" onClick={onClear}>Clear history</button></div>{history.length ? <div className="history-list">{history.map((item) => <div key={item.id}><span>{item.formula}<small>{item.symbol}</small></span><b>{item.result}</b><time>{item.time}</time></div>)}</div> : <p className="empty-history">Your recent calculations will appear here.</p>}</section>
}
