import { useMemo, useState } from 'react'

const fact = (n) => {
  let result = 1
  for (let i = 2; i <= Number(n); i += 1) result *= i
  return result
}

const formulas = [
  { id: 1, name: "Pythagorean Theorem", symbol: "c = √(a² + b²)", category: "Math", description: "Find the hypotenuse of a right triangle from its two legs.", variables: [{ key: "a", label: "Leg a", unit: "" }, { key: "b", label: "Leg b", unit: "" }], calculate: ({ a, b }) => Math.sqrt(Number(a) ** 2 + Number(b) ** 2), resultLabel: "Hypotenuse", resultUnit: "" },
  { id: 2, name: "Circle Area", symbol: "A = πr²", category: "Math", description: "Calculate the area enclosed by a circle.", variables: [{ key: "r", label: "Radius", unit: "m" }], calculate: ({ r }) => Math.PI * Number(r) ** 2, resultLabel: "Area", resultUnit: "m²" },
  { id: 3, name: "Circle Circumference", symbol: "C = 2πr", category: "Math", description: "Calculate the distance around a circle.", variables: [{ key: "r", label: "Radius", unit: "m" }], calculate: ({ r }) => 2 * Math.PI * Number(r), resultLabel: "Circumference", resultUnit: "m" },
  { id: 4, name: "Triangle Area", symbol: "A = ½bh", category: "Math", description: "Find the area of a triangle from its base and height.", variables: [{ key: "b", label: "Base", unit: "m" }, { key: "h", label: "Height", unit: "m" }], calculate: ({ b, h }) => 0.5 * Number(b) * Number(h), resultLabel: "Area", resultUnit: "m²" },
  { id: 5, name: "Rectangle Area", symbol: "A = lw", category: "Math", description: "Calculate the area of a rectangle.", variables: [{ key: "l", label: "Length", unit: "m" }, { key: "w", label: "Width", unit: "m" }], calculate: ({ l, w }) => Number(l) * Number(w), resultLabel: "Area", resultUnit: "m²" },
  { id: 6, name: "Sphere Volume", symbol: "V = ⁴⁄₃πr³", category: "Math", description: "Calculate the volume of a sphere from its radius.", variables: [{ key: "r", label: "Radius", unit: "m" }], calculate: ({ r }) => (4 / 3) * Math.PI * Number(r) ** 3, resultLabel: "Volume", resultUnit: "m³" },
  { id: 7, name: "Quadratic Formula", symbol: "x = (−b ± √(b²−4ac)) / 2a", category: "Math", description: "Find the real roots of ax² + bx + c = 0.", variables: [{ key: "a", label: "Coefficient a", unit: "" }, { key: "b", label: "Coefficient b", unit: "" }, { key: "c", label: "Coefficient c", unit: "" }], calculate: ({ a, b, c }) => { const d = Number(b) ** 2 - 4 * Number(a) * Number(c); if (d < 0 || Number(a) === 0) return null; return [(-Number(b) + Math.sqrt(d)) / (2 * Number(a)), (-Number(b) - Math.sqrt(d)) / (2 * Number(a))] }, resultLabel: "Roots", resultUnit: "" },
  { id: 8, name: "Distance Between Points", symbol: "d = √((x₂−x₁)² + (y₂−y₁)²)", category: "Math", description: "Find the straight-line distance between two points.", variables: [{ key: "x1", label: "x₁", unit: "" }, { key: "y1", label: "y₁", unit: "" }, { key: "x2", label: "x₂", unit: "" }, { key: "y2", label: "y₂", unit: "" }], calculate: ({ x1, y1, x2, y2 }) => Math.hypot(Number(x2) - Number(x1), Number(y2) - Number(y1)), resultLabel: "Distance", resultUnit: "units" },
  { id: 9, name: "Slope", symbol: "m = (y₂−y₁)/(x₂−x₁)", category: "Math", description: "Calculate the gradient of a line through two points.", variables: [{ key: "x1", label: "x₁", unit: "" }, { key: "y1", label: "y₁", unit: "" }, { key: "x2", label: "x₂", unit: "" }, { key: "y2", label: "y₂", unit: "" }], calculate: ({ x1, y1, x2, y2 }) => Number(x2) === Number(x1) ? null : (Number(y2) - Number(y1)) / (Number(x2) - Number(x1)), resultLabel: "Slope", resultUnit: "" },
  { id: 10, name: "Permutations", symbol: "P(n,r) = n!/(n−r)!", category: "Math", description: "Count ordered arrangements of r items selected from n.", variables: [{ key: "n", label: "Total n", unit: "" }, { key: "r", label: "Selected r", unit: "" }], calculate: ({ n, r }) => Number(r) > Number(n) ? null : fact(n) / fact(Number(n) - Number(r)), resultLabel: "Permutations", resultUnit: "" },
  { id: 11, name: "Newton's Second Law", symbol: "F = ma", category: "Physics", description: "Find the net force acting on an object.", variables: [{ key: "m", label: "Mass", unit: "kg" }, { key: "a", label: "Acceleration", unit: "m/s²" }], calculate: ({ m, a }) => Number(m) * Number(a), resultLabel: "Force", resultUnit: "N" },
  { id: 12, name: "Kinetic Energy", symbol: "Eₖ = ½mv²", category: "Physics", description: "Calculate the energy an object has because of its motion.", variables: [{ key: "m", label: "Mass", unit: "kg" }, { key: "v", label: "Velocity", unit: "m/s" }], calculate: ({ m, v }) => 0.5 * Number(m) * Number(v) ** 2, resultLabel: "Energy", resultUnit: "J" },
  { id: 13, name: "Gravitational Potential Energy", symbol: "Eₚ = mgh", category: "Physics", description: "Find the energy stored by an object due to its height.", variables: [{ key: "m", label: "Mass", unit: "kg" }, { key: "g", label: "Gravity", unit: "m/s²" }, { key: "h", label: "Height", unit: "m" }], calculate: ({ m, g, h }) => Number(m) * Number(g) * Number(h), resultLabel: "Potential energy", resultUnit: "J" },
  { id: 14, name: "Momentum", symbol: "p = mv", category: "Physics", description: "Calculate the linear momentum of a moving object.", variables: [{ key: "m", label: "Mass", unit: "kg" }, { key: "v", label: "Velocity", unit: "m/s" }], calculate: ({ m, v }) => Number(m) * Number(v), resultLabel: "Momentum", resultUnit: "kg·m/s" },
  { id: 15, name: "Density", symbol: "ρ = m/V", category: "Physics", description: "Find mass per unit volume.", variables: [{ key: "m", label: "Mass", unit: "kg" }, { key: "v", label: "Volume", unit: "m³" }], calculate: ({ m, v }) => Number(v) === 0 ? null : Number(m) / Number(v), resultLabel: "Density", resultUnit: "kg/m³" },
  { id: 16, name: "Pressure", symbol: "P = F/A", category: "Physics", description: "Calculate force distributed over an area.", variables: [{ key: "f", label: "Force", unit: "N" }, { key: "a", label: "Area", unit: "m²" }], calculate: ({ f, a }) => Number(a) === 0 ? null : Number(f) / Number(a), resultLabel: "Pressure", resultUnit: "Pa" },
  { id: 17, name: "Work", symbol: "W = Fd cosθ", category: "Physics", description: "Find work done by a force at an angle.", variables: [{ key: "f", label: "Force", unit: "N" }, { key: "d", label: "Distance", unit: "m" }, { key: "theta", label: "Angle θ", unit: "deg" }], calculate: ({ f, d, theta }) => Number(f) * Number(d) * Math.cos(Number(theta) * Math.PI / 180), resultLabel: "Work", resultUnit: "J" },
  { id: 18, name: "Gravitational Force", symbol: "F = Gm₁m₂/r²", category: "Physics", description: "Calculate the force between two masses.", variables: [{ key: "m1", label: "Mass m₁", unit: "kg" }, { key: "m2", label: "Mass m₂", unit: "kg" }, { key: "r", label: "Distance", unit: "m" }], calculate: ({ m1, m2, r }) => Number(r) === 0 ? null : (6.6743e-11 * Number(m1) * Number(m2)) / Number(r) ** 2, resultLabel: "Force", resultUnit: "N" },
  { id: 19, name: "Coulomb's Law", symbol: "F = k|q₁q₂|/r²", category: "Physics", description: "Find the electric force between two point charges.", variables: [{ key: "q1", label: "Charge q₁", unit: "C" }, { key: "q2", label: "Charge q₂", unit: "C" }, { key: "r", label: "Distance", unit: "m" }], calculate: ({ q1, q2, r }) => Number(r) === 0 ? null : (8.9875517923e9 * Math.abs(Number(q1) * Number(q2))) / Number(r) ** 2, resultLabel: "Electric force", resultUnit: "N" },
  { id: 20, name: "Wave Speed", symbol: "v = fλ", category: "Physics", description: "Calculate wave speed from frequency and wavelength.", variables: [{ key: "f", label: "Frequency", unit: "Hz" }, { key: "lambda", label: "Wavelength", unit: "m" }], calculate: ({ f, lambda }) => Number(f) * Number(lambda), resultLabel: "Wave speed", resultUnit: "m/s" },
  { id: 21, name: "Hooke's Law", symbol: "F = kx", category: "Physics", description: "Find the restoring force of an ideal spring.", variables: [{ key: "k", label: "Spring constant", unit: "N/m" }, { key: "x", label: "Extension", unit: "m" }], calculate: ({ k, x }) => Number(k) * Number(x), resultLabel: "Spring force", resultUnit: "N" },
  { id: 22, name: "Ideal Gas Law", symbol: "PV = nRT", category: "Physics", description: "Calculate pressure from amount, temperature, and volume.", variables: [{ key: "n", label: "Amount n", unit: "mol" }, { key: "t", label: "Temperature", unit: "K" }, { key: "v", label: "Volume", unit: "m³" }], calculate: ({ n, t, v }) => Number(v) === 0 ? null : (Number(n) * 8.314462618 * Number(t)) / Number(v), resultLabel: "Pressure", resultUnit: "Pa" },
  { id: 23, name: "Electric Power", symbol: "P = VI", category: "Physics", description: "Calculate electrical power from voltage and current.", variables: [{ key: "v", label: "Voltage", unit: "V" }, { key: "i", label: "Current", unit: "A" }], calculate: ({ v, i }) => Number(v) * Number(i), resultLabel: "Power", resultUnit: "W" },
  { id: 24, name: "Electric Charge", symbol: "Q = It", category: "Physics", description: "Find charge moved by a current over time.", variables: [{ key: "i", label: "Current", unit: "A" }, { key: "t", label: "Time", unit: "s" }], calculate: ({ i, t }) => Number(i) * Number(t), resultLabel: "Charge", resultUnit: "C" },
  { id: 25, name: "Ohm's Law", symbol: "V = IR", category: "Engineering", description: "Find voltage from current and resistance.", variables: [{ key: "i", label: "Current", unit: "A" }, { key: "r", label: "Resistance", unit: "Ω" }], calculate: ({ i, r }) => Number(i) * Number(r), resultLabel: "Voltage", resultUnit: "V" },
  { id: 26, name: "Electrical Resistance", symbol: "R = ρL/A", category: "Engineering", description: "Calculate the resistance of a uniform conductor.", variables: [{ key: "rho", label: "Resistivity", unit: "Ω·m" }, { key: "l", label: "Length", unit: "m" }, { key: "a", label: "Area", unit: "m²" }], calculate: ({ rho, l, a }) => Number(a) === 0 ? null : Number(rho) * Number(l) / Number(a), resultLabel: "Resistance", resultUnit: "Ω" },
  { id: 27, name: "Normal Stress", symbol: "σ = F/A", category: "Engineering", description: "Find internal force per unit cross-sectional area.", variables: [{ key: "f", label: "Force", unit: "N" }, { key: "a", label: "Cross-section", unit: "m²" }], calculate: ({ f, a }) => Number(a) === 0 ? null : Number(f) / Number(a), resultLabel: "Stress", resultUnit: "Pa" },
  { id: 28, name: "Normal Strain", symbol: "ε = ΔL/L", category: "Engineering", description: "Calculate deformation relative to original length.", variables: [{ key: "dl", label: "Change ΔL", unit: "m" }, { key: "l", label: "Original L", unit: "m" }], calculate: ({ dl, l }) => Number(l) === 0 ? null : Number(dl) / Number(l), resultLabel: "Strain", resultUnit: "" },
  { id: 29, name: "Flow Rate", symbol: "Q = V/t", category: "Engineering", description: "Find volume of fluid flowing per unit time.", variables: [{ key: "v", label: "Volume", unit: "m³" }, { key: "t", label: "Time", unit: "s" }], calculate: ({ v, t }) => Number(t) === 0 ? null : Number(v) / Number(t), resultLabel: "Flow rate", resultUnit: "m³/s" },
  { id: 30, name: "Reynolds Number", symbol: "Re = ρvD/μ", category: "Engineering", description: "Classify the flow regime of a fluid.", variables: [{ key: "rho", label: "Density ρ", unit: "kg/m³" }, { key: "v", label: "Velocity", unit: "m/s" }, { key: "d", label: "Diameter", unit: "m" }, { key: "mu", label: "Viscosity μ", unit: "Pa·s" }], calculate: ({ rho, v, d, mu }) => Number(mu) === 0 ? null : Number(rho) * Number(v) * Number(d) / Number(mu), resultLabel: "Reynolds number", resultUnit: "" },
  { id: 31, name: "Thermal Expansion", symbol: "ΔL = αLΔT", category: "Engineering", description: "Calculate length change caused by temperature change.", variables: [{ key: "alpha", label: "Coefficient α", unit: "1/K" }, { key: "l", label: "Original length", unit: "m" }, { key: "dt", label: "Temperature ΔT", unit: "K" }], calculate: ({ alpha, l, dt }) => Number(alpha) * Number(l) * Number(dt), resultLabel: "Length change", resultUnit: "m" },
  { id: 32, name: "Factor of Safety", symbol: "FoS = Strength/Stress", category: "Engineering", description: "Compare material strength with applied stress.", variables: [{ key: "strength", label: "Material strength", unit: "Pa" }, { key: "stress", label: "Applied stress", unit: "Pa" }], calculate: ({ strength, stress }) => Number(stress) === 0 ? null : Number(strength) / Number(stress), resultLabel: "Safety factor", resultUnit: "" },
  { id: 33, name: "Molarity", symbol: "M = n/V", category: "Chemistry", description: "Calculate concentration in moles per litre.", variables: [{ key: "n", label: "Moles", unit: "mol" }, { key: "v", label: "Volume", unit: "L" }], calculate: ({ n, v }) => Number(v) === 0 ? null : Number(n) / Number(v), resultLabel: "Molarity", resultUnit: "mol/L" },
  { id: 34, name: "pH", symbol: "pH = −log₁₀[H⁺]", category: "Chemistry", description: "Find acidity from hydrogen ion concentration.", variables: [{ key: "h", label: "[H⁺] concentration", unit: "mol/L" }], calculate: ({ h }) => Number(h) <= 0 ? null : -Math.log10(Number(h)), resultLabel: "pH", resultUnit: "" },
  { id: 35, name: "Dilution Equation", symbol: "M₁V₁ = M₂V₂", category: "Chemistry", description: "Find final concentration after dilution.", variables: [{ key: "m1", label: "Initial M₁", unit: "mol/L" }, { key: "v1", label: "Initial V₁", unit: "L" }, { key: "v2", label: "Final V₂", unit: "L" }], calculate: ({ m1, v1, v2 }) => Number(v2) === 0 ? null : Number(m1) * Number(v1) / Number(v2), resultLabel: "Final molarity", resultUnit: "mol/L" },
  { id: 36, name: "Mass Percent", symbol: "%m/m = mass solute/mass solution × 100", category: "Chemistry", description: "Calculate the percentage of solute by mass.", variables: [{ key: "solute", label: "Solute mass", unit: "g" }, { key: "solution", label: "Solution mass", unit: "g" }], calculate: ({ solute, solution }) => Number(solution) === 0 ? null : Number(solute) / Number(solution) * 100, resultLabel: "Mass percent", resultUnit: "%" },
  { id: 37, name: "Z-Score", symbol: "z = (x−μ)/σ", category: "Statistics", description: "Standardize a value using the mean and standard deviation.", variables: [{ key: "x", label: "Value x", unit: "" }, { key: "mean", label: "Mean μ", unit: "" }, { key: "sd", label: "Std. deviation σ", unit: "" }], calculate: ({ x, mean, sd }) => Number(sd) === 0 ? null : (Number(x) - Number(mean)) / Number(sd), resultLabel: "Z-score", resultUnit: "" },
  { id: 38, name: "Arithmetic Mean", symbol: "x̄ = Σx/n", category: "Statistics", description: "Calculate the average of four values.", variables: [{ key: "x1", label: "Value 1", unit: "" }, { key: "x2", label: "Value 2", unit: "" }, { key: "x3", label: "Value 3", unit: "" }, { key: "x4", label: "Value 4", unit: "" }], calculate: ({ x1, x2, x3, x4 }) => (Number(x1) + Number(x2) + Number(x3) + Number(x4)) / 4, resultLabel: "Mean", resultUnit: "" },
  { id: 39, name: "Percentage Change", symbol: "%Δ = (new−old)/old × 100", category: "Statistics", description: "Measure relative increase or decrease between two values.", variables: [{ key: "old", label: "Original value", unit: "" }, { key: "newValue", label: "New value", unit: "" }], calculate: ({ old, newValue }) => Number(old) === 0 ? null : (Number(newValue) - Number(old)) / Number(old) * 100, resultLabel: "Percentage change", resultUnit: "%" },
  { id: 40, name: "Compound Interest", symbol: "A = P(1 + r/n)ⁿᵗ", category: "Finance", description: "Calculate balance with periodic compound interest.", variables: [{ key: "p", label: "Principal P", unit: "$" }, { key: "r", label: "Annual rate", unit: "%" }, { key: "n", label: "Compounds/year", unit: "" }, { key: "t", label: "Time", unit: "years" }], calculate: ({ p, r, n, t }) => Number(p) * (1 + Number(r) / 100 / Number(n)) ** (Number(n) * Number(t)), resultLabel: "Future value", resultUnit: "$" },
  { id: 41, name: "Simple Interest", symbol: "I = Prt", category: "Finance", description: "Calculate interest earned without compounding.", variables: [{ key: "p", label: "Principal P", unit: "$" }, { key: "r", label: "Annual rate", unit: "%" }, { key: "t", label: "Time", unit: "years" }], calculate: ({ p, r, t }) => Number(p) * Number(r) / 100 * Number(t), resultLabel: "Interest", resultUnit: "$" },
  { id: 42, name: "Future Value", symbol: "FV = PV(1+r)ᵗ", category: "Finance", description: "Project a present value forward using an annual growth rate.", variables: [{ key: "pv", label: "Present value", unit: "$" }, { key: "r", label: "Growth rate", unit: "%" }, { key: "t", label: "Time", unit: "years" }], calculate: ({ pv, r, t }) => Number(pv) * (1 + Number(r) / 100) ** Number(t), resultLabel: "Future value", resultUnit: "$" },
  { id: 43, name: "Celsius to Fahrenheit", symbol: "°F = (°C × 9/5) + 32", category: "Math", description: "Convert a temperature from Celsius to Fahrenheit.", variables: [{ key: "c", label: "Celsius", unit: "°C" }], calculate: ({ c }) => Number(c) * 9 / 5 + 32, resultLabel: "Fahrenheit", resultUnit: "°F" },
  { id: 44, name: "Degrees to Radians", symbol: "rad = degrees × π/180", category: "Math", description: "Convert an angle from degrees to radians.", variables: [{ key: "degrees", label: "Degrees", unit: "°" }], calculate: ({ degrees }) => Number(degrees) * Math.PI / 180, resultLabel: "Radians", resultUnit: "rad" },
]

const categories = ['All', 'Math', 'Physics', 'Engineering', 'Chemistry', 'Statistics', 'Finance']
const icons = { Math: 'π', Physics: 'Φ', Engineering: 'Ω', Chemistry: '⚗', Statistics: 'σ', Finance: '$' }

function App() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('All')
  const [selectedId, setSelectedId] = useState(11)
  const [favorites, setFavorites] = useState([])
  const [values, setValues] = useState({})
  const [result, setResult] = useState(null)
  const [error, setError] = useState('')
  const [isDark, setIsDark] = useState(false)

  const filteredFormulas = useMemo(() => formulas.filter((formula) => {
    const searchable = `${formula.name} ${formula.description} ${formula.symbol} ${formula.category}`.toLowerCase()
    return (category === 'All' || formula.category === category) && searchable.includes(query.toLowerCase())
  }), [category, query])
  const selectedFormula = formulas.find((formula) => formula.id === selectedId) || formulas[0]
  const isFavorite = favorites.includes(selectedFormula.id)

  const selectFormula = (id) => { setSelectedId(id); setResult(null); setError(''); setValues({}) }
  const calculate = () => {
    setError('')
    if (!selectedFormula.variables.every(({ key }) => values[key] !== undefined && values[key] !== '')) { setError('Please fill in every field.'); return }
    const calculated = selectedFormula.calculate(values)
    if (calculated === null || Number.isNaN(calculated)) { setError('These values cannot produce a valid result.'); setResult(null); return }
    setResult(calculated)
  }
  const toggleFavorite = (id) => setFavorites((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const formattedResult = Array.isArray(result) ? result.map((item) => item.toFixed(3)).join('  or  ') : Number(result).toLocaleString('en-US', { maximumFractionDigits: 4 })

  return (
    <div className={isDark ? 'app dark' : 'app'}>
      <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">∑</span><span><strong>Formula</strong><em>Hub</em></span></a><nav className="nav-links"><a className="active" href="#library">Library</a><a href="#calculator">Calculator</a><a href="#about">About</a></nav><button className="theme-button" onClick={() => setIsDark((current) => !current)} aria-label="Toggle theme">{isDark ? '☀' : '◐'}</button></header>
      <main id="top">
        <section className="hero"><div className="hero-copy"><span className="eyebrow">Your intelligent science reference</span><h1>Every formula you need.<br /><span>One place.</span></h1><p>Explore essential formulas in mathematics, physics, engineering, chemistry, statistics, and finance. Understand them, then calculate your answer instantly.</p><div className="hero-stats"><span><b>{String(formulas.length).padStart(2, '0')}</b> formulas</span><span><b>06</b> disciplines</span><span><b>∞</b> ways to learn</span></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="formula-orb">π<br /><small>F = ma</small></div><span className="floating-chip chip-one">∫ f(x) dx</span><span className="floating-chip chip-two">Δ = b² − 4ac</span></div></section>
        <section className="workspace" id="library"><div className="section-heading"><div><span className="section-kicker">Explore and learn</span><h2>Formula library</h2></div><span className="count-badge">{filteredFormulas.length} formulas</span></div><div className="toolbar"><label className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search a formula, concept, or symbol..." aria-label="Search formulas" />{query && <button onClick={() => setQuery('')} aria-label="Clear search">×</button>}</label><div className="category-tabs">{categories.map((item) => <button key={item} className={category === item ? 'selected' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div></div>
          <div className="content-grid"><div className="formula-list">{filteredFormulas.length ? filteredFormulas.map((formula) => <button key={formula.id} className={`formula-card ${selectedFormula.id === formula.id ? 'active-card' : ''}`} onClick={() => selectFormula(formula.id)}><span className={`category-dot dot-${formula.category}`}>{icons[formula.category]}</span><span className="card-info"><strong>{formula.name}</strong><small>{formula.category}</small></span><span className="card-symbol">{formula.symbol}</span><span className="card-arrow">→</span></button>) : <div className="empty-state">No formulas found. Try another search.</div>}</div>
            <aside className="details-card" id="calculator"><div className="details-top"><span className={`category-dot large dot-${selectedFormula.category}`}>{icons[selectedFormula.category]}</span><div><span className="section-kicker">{selectedFormula.category}</span><h3>{selectedFormula.name}</h3></div><button className={`favorite ${isFavorite ? 'is-favorite' : ''}`} onClick={() => toggleFavorite(selectedFormula.id)} aria-label="Add to favorites">{isFavorite ? '★' : '☆'}</button></div><div className="formula-display">{selectedFormula.symbol}</div><p className="formula-description">{selectedFormula.description}</p><div className="divider" /><h4>Calculate your result</h4><div className="inputs-grid">{selectedFormula.variables.map((variable) => <label key={variable.key}><span>{variable.label}</span><div className="input-wrap"><input type="number" value={values[variable.key] || ''} onChange={(event) => { setValues({ ...values, [variable.key]: event.target.value }); setError(''); setResult(null) }} placeholder="0" /><small>{variable.unit}</small></div></label>)}</div><button className="calculate-button" onClick={calculate}>Calculate now <span>↗</span></button>{error && <p className="error-message">{error}</p>}{result !== null && <div className="result-box"><span>{selectedFormula.resultLabel}</span><strong>{formattedResult} {selectedFormula.resultUnit}</strong></div>}</aside></div></section>
        <section className="about-section" id="about"><span className="section-kicker">Built for curious minds</span><h2>Understand the formula, not just the answer.</h2><p>FormulaHub helps you move from theory to practice with a clear reference and a simple calculator for every formula.</p></section>
      </main><footer><span>FormulaHub © 2026</span><span>Made for learning and discovery</span></footer>
    </div>
  )
}

export default App
