import { useMemo, useState } from 'react'

const fact = (n) => {
  let result = 1
  for (let i = 2; i <= Number(n); i += 1) result *= i
  return result
}

const formulas = [
  { id: 1, name: "Pythagorean Theorem", symbol: "c = √(a² + b²)", category: "Math", description: "Find the hypotenuse of a right triangle from its two legs.", variables: [{ key: "a", label: "Leg a", unit: "" }, { key: "b", label: "Leg b", unit: "" }], calculate: ({ a, b }) => Math.sqrt(Number(a) ** 2 + Number(b) ** 2), resultLabel: "Hypotenuse", resultUnit: "" },
  { id: 2, name: "Circle Area", symbol: "A = πr²", category: "Math", description: "Calculate the area enclosed by a circle.", variables: [{ key: "r", label: "Radius", unit: "m" }], calculate: ({ r }) => Math.PI * Number(r) ** 2, resultLabel: "Area", resultUnit: "m²" },
  { id: 3, name: "Circle Circumference", symbol: "C = 2πr", category: "Math", description: "Calculate the distance around a circle.", variables: [{ key: "r", label: "Radius", unit: "m" }], calculate: ({ r }) => 2 * Math.PI * Number(r), resultLabel: "Circumference", resultUnit: "m" },
  { id: 4, name: "Triangle Area", symbol: "A = ½bh", category: "Math", description: "Find the area of a triangle from its base and height.", variables: [{ key: "b", label: "Base", unit: "m" }, { key: "h", label: "Height", unit: "m" }], calculate: ({ b, h }) => 0.5 * Number(b) * Number(h), resultLabel: "Area", resultUnit: "m²" },
  { id: 5, name: "Rectangle Area", symbol: "A = lw", category: "Math", description: "Calculate the area of a rectangle.", variables: [{ key: "l", label: "Length", unit: "m" }, { key: "w", label: "Width", unit: "m" }], calculate: ({ l, w }) => Number(l) * Number(w), resultLabel: "Area", resultUnit: "m²" },
  { id: 6, name: "Sphere Volume", symbol: "V = ⁴⁄₃πr³", category: "Math", description: "Calculate the volume of a sphere from its radius.", variables: [{ key: "r", label: "Radius", unit: "m" }], calculate: ({ r }) => (4 / 3) * Math.PI * Number(r) ** 3, resultLabel: "Volume", resultUnit: "m³" },
  { id: 7, name: "Quadratic Formula", symbol: "x = (−b ± √(b²−4ac)) / 2a", category: "Math", description: "Find the real roots of ax² + bx + c = 0.", variables: [{ key: "a", label: "Coefficient a", unit: "" }, { key: "b", label: "Coefficient b", unit: "" }, { key: "c", label: "Coefficient c", unit: "" }], calculate: ({ a, b, c }) => { const d = Number(b) ** 2 - 4 * Number(a) * Number(c); if (d < 0 || Number(a) === 0) return null; return [(-Number(b) + Math.sqrt(d)) / (2 * Number(a)), (-Number(b) - Math.sqrt(d)) / (2 * Number(a))] }, resultLabel: "Roots", resultUnit: "" },
  { id: 8, name: "Distance Between Points", symbol: "d = √((x₂−x₁)² + (y₂−y₁)²)", category: "Math", description: "Find the straight-line distance between two points.", variables: [{ key: "x1", label: "x₁", unit: "" }, { key: "y1", label: "y₁", unit: "" }, { key: "x2", label: "x₂", unit: "" }, { key: "y2", label: "y₂", unit: "" }], calculate: ({ x1, y1, x2, y2 }) => Math.hypot(Number(x2) - Number(x1), Number(y2) - Number(y1)), resultLabel: "Distance", resultUnit: "units" },
  { id: 9, name: "Slope", symbol: "m = (y₂−y₁)/(x₂−x₁)", category: "Math", description: "Calculate the gradient of a line through two points.", variables: [{ key: "x1", label: "x₁", unit: "" }, { key: "y1", label: "y₁", unit: "" }, { key: "x2", label: "x₂", unit: "" }, { key: "y2", label: "y₂", unit: "" }], calculate: ({ x1, y1, x2, y2 }) => Number(x2) === Number(x1) ? null : (Number(y2) - Number(y1)) / (Number(x2) - Number(x1)), resultLabel: "Slope", resultUnit: "" },
  { id: 10, name: "Permutations", symbol: "P(n,r) = n!/(n−r)!", category: "Math", description: "Count ordered arrangements of r items selected from n.", variables: [{ key: "n", label: "Total n", unit: "" }, { key: "r", label: "Selected r", unit: "" }], calculate: ({ n, r }) => Number(r) > Number(n) ? null : fact(n) / fact(Number(n) - Number(r)), resultLabel: "Permutations", resultUnit: "" },
  { id: 11, name: "Newton's Second Law", symbol: "F = ma", category: "Physics", description: "Find the net force acting on an object.", variables: [{ key: "m", label: "Mass", unit: "kg" }, { key: "a", label: "Acceleration", unit: "m/s²" }], calculate: ({ m, a }) => Number(m) * Number(a), resultLabel: "Force", resultUnit: "N" },
  { id: 12, name: "Kinetic Energy", symbol: "Eₖ = ½mv²", category: "Physics", description: "Calculate the energy an object has because of its motion.", variables: [{ key: "m", label: "Mass", unit: "kg" }, { key: "v", label: "Velocity", unit: "m/s" }], calculate: ({ m, v }) => 0.5 * Number(m) * Number(v) ** 2, resultLabel: "Energy", resultUnit: "J" },
  { id: 13, name: "Gravitational Potential Energy", symbol: "Eₚ = mgh", category: "Physics", description: "Find the energy stored by an object due to its height.", variables: [{ key: "m", label: "Mass", unit: "kg" }, { key: "g", label: "Gravity", unit: "m/s²" }, { key: "h", label: "Height", unit: "m" }], calculate: ({ m, g, h }) => Number(m) * Number(g) * Number(h), resultLabel: "Potential energy", resultUnit: "J" },
  { id: 14, name: "Momentum", symbol: "p = mv", category: "Physics", description: "Calculate the linear momentum of a moving object.", variables: [{ key: "m", label: "Mass", unit: "kg" }, { key: "v", label: "Velocity", unit: "m/s" }], calculate: ({ m, v }) => Number(m) * Number(v), resultLabel: "Momentum", resultUnit: "kg·m/s" },
  { id: 15, name: "Density", symbol: "ρ = m/V", category: "Physics", description: "Find mass per unit volume.", variables: [{ key: "m", label: "Mass", unit: "kg" }, { key: "v", label: "Volume", unit: "m³" }], calculate: ({ m, v }) => Number(v) === 0 ? null : Number(m) / Number(v), resultLabel: "Density", resultUnit: "kg/m³" },
  { id: 16, name: "Pressure", symbol: "P = F/A", category: "Physics", description: "Calculate force distributed over an area.", variables: [{ key: "f", label: "Force", unit: "N" }, { key: "a", label: "Area", unit: "m²" }], calculate: ({ f, a }) => Number(a) === 0 ? null : Number(f) / Number(a), resultLabel: "Pressure", resultUnit: "Pa" },
  { id: 17, name: "Work", symbol: "W = Fd cosθ", category: "Physics", description: "Find work done by a force at an angle.", variables: [{ key: "f", label: "Force", unit: "N" }, { key: "d", label: "Distance", unit: "m" }, { key: "theta", label: "Angle θ", unit: "deg" }], calculate: ({ f, d, theta }) => Number(f) * Number(d) * Math.cos(Number(theta) * Math.PI / 180), resultLabel: "Work", resultUnit: "J" },
  { id: 18, name: "Gravitational Force", symbol: "F = Gm₁m₂/r²", category: "Physics", description: "Calculate the force between two masses.", variables: [{ key: "m1", label: "Mass m₁", unit: "kg" }, { key: "m2", label: "Mass m₂", unit: "kg" }, { key: "r", label: "Distance", unit: "m" }], calculate: ({ m1, m2, r }) => Number(r) === 0 ? null : (6.6743e-11 * Number(m1) * Number(m2)) / Number(r) ** 2, resultLabel: "Force", resultUnit: "N" },
  { id: 19, name: "Coulomb's Law", symbol: "F = k|q₁q₂|/r²", category: "Physics", description: "Find the electric force between two point charges.", variables: [{ key: "q1", label: "Charge q₁", unit: "C" }, { key: "q2", label: "Charge q₂", unit: "C" }, { key: "r", label: "Distance", unit: "m" }], calculate: ({ q1, q2, r }) => Number(r) === 0 ? null : (8.9875517923e9 * Math.abs(Number(q1) * Number(q2))) / Number(r) ** 2, resultLabel: "Electric force", resultUnit: "N" },
  { id: 20, name: "Wave Speed", symbol: "v = fλ", category: "Physics", description: "Calculate wave speed from frequency and wavelength.", variables: [{ key: "f", label: "Frequency", unit: "Hz" }, { key: "lambda", label: "Wavelength", unit: "m" }], calculate: ({ f, lambda }) => Number(f) * Number(lambda), resultLabel: "Wave speed", resultUnit: "m/s" },
  { id: 21, name: "Hooke's Law", symbol: "F = kx", category: "Physics", description: "Find the restoring force of an ideal spring.", variables: [{ key: "k", label: "Spring constant", unit: "N/m" }, { key: "x", label: "Extension", unit: "m" }], calculate: ({ k, x }) => Number(k) * Number(x), resultLabel: "Spring force", resultUnit: "N" },
  { id: 22, name: "Ideal Gas Law", symbol: "PV = nRT", category: "Physics", description: "Calculate pressure from amount, temperature, and volume.", variables: [{ key: "n", label: "Amount n", unit: "mol" }, { key: "t", label: "Temperature", unit: "K" }, { key: "v", label: "Volume", unit: "m³" }], calculate: ({ n, t, v }) => Number(v) === 0 ? null : (Number(n) * 8.314462618 * Number(t)) / Number(v), resultLabel: "Pressure", resultUnit: "Pa" },
  { id: 23, name: "Electric Power", symbol: "P = VI", category: "Physics", description: "Calculate electrical power from voltage and current.", variables: [{ key: "v", label: "Voltage", unit: "V" }, { key: "i", label: "Current", unit: "A" }], calculate: ({ v, i }) => Number(v) * Number(i), resultLabel: "Power", resultUnit: "W" },
  { id: 24, name: "Electric Charge", symbol: "Q = It", category: "Physics", description: "Find charge moved by a current over time.", variables: [{ key: "i", label: "Current", unit: "A" }, { key: "t", label: "Time", unit: "s" }], calculate: ({ i, t }) => Number(i) * Number(t), resultLabel: "Charge", resultUnit: "C" },
  { id: 25, name: "Ohm's Law", symbol: "V = IR", category: "Engineering", description: "Find voltage from current and resistance.", variables: [{ key: "i", label: "Current", unit: "A" }, { key: "r", label: "Resistance", unit: "Ω" }], calculate: ({ i, r }) => Number(i) * Number(r), resultLabel: "Voltage", resultUnit: "V" },
  { id: 26, name: "Electrical Resistance", symbol: "R = ρL/A", category: "Engineering", description: "Calculate the resistance of a uniform conductor.", variables: [{ key: "rho", label: "Resistivity", unit: "Ω·m" }, { key: "l", label: "Length", unit: "m" }, { key: "a", label: "Area", unit: "m²" }], calculate: ({ rho, l, a }) => Number(a) === 0 ? null : Number(rho) * Number(l) / Number(a), resultLabel: "Resistance", resultUnit: "Ω" },
  { id: 27, name: "Normal Stress", symbol: "σ = F/A", category: "Engineering", description: "Find internal force per unit cross-sectional area.", variables: [{ key: "f", label: "Force", unit: "N" }, { key: "a", label: "Cross-section", unit: "m²" }], calculate: ({ f, a }) => Number(a) === 0 ? null : Number(f) / Number(a), resultLabel: "Stress", resultUnit: "Pa" },
  { id: 28, name: "Normal Strain", symbol: "ε = ΔL/L", category: "Engineering", description: "Calculate deformation relative to original length.", variables: [{ key: "dl", label: "Change ΔL", unit: "m" }, { key: "l", label: "Original L", unit: "m" }], calculate: ({ dl, l }) => Number(l) === 0 ? null : Number(dl) / Number(l), resultLabel: "Strain", resultUnit: "" },
  { id: 29, name: "Flow Rate", symbol: "Q = V/t", category: "Engineering", description: "Find volume of fluid flowing per unit time.", variables: [{ key: "v", label: "Volume", unit: "m³" }, { key: "t", label: "Time", unit: "s" }], calculate: ({ v, t }) => Number(t) === 0 ? null : Number(v) / Number(t), resultLabel: "Flow rate", resultUnit: "m³/s" },
  { id: 30, name: "Reynolds Number", symbol: "Re = ρvD/μ", category: "Engineering", description: "Classify the flow regime of a fluid.", variables: [{ key: "rho", label: "Density ρ", unit: "kg/m³" }, { key: "v", label: "Velocity", unit: "m/s" }, { key: "d", label: "Diameter", unit: "m" }, { key: "mu", label: "Viscosity μ", unit: "Pa·s" }], calculate: ({ rho, v, d, mu }) => Number(mu) === 0 ? null : Number(rho) * Number(v) * Number(d) / Number(mu), resultLabel: "Reynolds number", resultUnit: "" },
  { id: 31, name: "Thermal Expansion", symbol: "ΔL = αLΔT", category: "Engineering", description: "Calculate length change caused by temperature change.", variables: [{ key: "alpha", label: "Coefficient α", unit: "1/K" }, { key: "l", label: "Original length", unit: "m" }, { key: "dt", label: "Temperature ΔT", unit: "K" }], calculate: ({ alpha, l, dt }) => Number(alpha) * Number(l) * Number(dt), resultLabel: "Length change", resultUnit: "m" },
  { id: 32, name: "Factor of Safety", symbol: "FoS = Strength/Stress", category: "Engineering", description: "Compare material strength with applied stress.", variables: [{ key: "strength", label: "Material strength", unit: "Pa" }, { key: "stress", label: "Applied stress", unit: "Pa" }], calculate: ({ strength, stress }) => Number(stress) === 0 ? null : Number(strength) / Number(stress), resultLabel: "Safety factor", resultUnit: "" },
  { id: 33, name: "Molarity", symbol: "M = n/V", category: "Chemistry", description: "Calculate concentration in moles per litre.", variables: [{ key: "n", label: "Moles", unit: "mol" }, { key: "v", label: "Volume", unit: "L" }], calculate: ({ n, v }) => Number(v) === 0 ? null : Number(n) / Number(v), resultLabel: "Molarity", resultUnit: "mol/L" },
  { id: 34, name: "pH", symbol: "pH = −log₁₀[H⁺]", category: "Chemistry", description: "Find acidity from hydrogen ion concentration.", variables: [{ key: "h", label: "[H⁺] concentration", unit: "mol/L" }], calculate: ({ h }) => Number(h) <= 0 ? null : -Math.log10(Number(h)), resultLabel: "pH", resultUnit: "" },
  { id: 35, name: "Dilution Equation", symbol: "M₁V₁ = M₂V₂", category: "Chemistry", description: "Find final concentration after dilution.", variables: [{ key: "m1", label: "Initial M₁", unit: "mol/L" }, { key: "v1", label: "Initial V₁", unit: "L" }, { key: "v2", label: "Final V₂", unit: "L" }], calculate: ({ m1, v1, v2 }) => Number(v2) === 0 ? null : Number(m1) * Number(v1) / Number(v2), resultLabel: "Final molarity", resultUnit: "mol/L" },
  { id: 36, name: "Mass Percent", symbol: "%m/m = mass solute/mass solution × 100", category: "Chemistry", description: "Calculate the percentage of solute by mass.", variables: [{ key: "solute", label: "Solute mass", unit: "g" }, { key: "solution", label: "Solution mass", unit: "g" }], calculate: ({ solute, solution }) => Number(solution) === 0 ? null : Number(solute) / Number(solution) * 100, resultLabel: "Mass percent", resultUnit: "%" },
  { id: 37, name: "Z-Score", symbol: "z = (x−μ)/σ", category: "Statistics", description: "Standardize a value using the mean and standard deviation.", variables: [{ key: "x", label: "Value x", unit: "" }, { key: "mean", label: "Mean μ", unit: "" }, { key: "sd", label: "Std. deviation σ", unit: "" }], calculate: ({ x, mean, sd }) => Number(sd) === 0 ? null : (Number(x) - Number(mean)) / Number(sd), resultLabel: "Z-score", resultUnit: "" },
  { id: 38, name: "Arithmetic Mean", symbol: "x̄ = Σx/n", category: "Statistics", description: "Calculate the average of four values.", variables: [{ key: "x1", label: "Value 1", unit: "" }, { key: "x2", label: "Value 2", unit: "" }, { key: "x3", label: "Value 3", unit: "" }, { key: "x4", label: "Value 4", unit: "" }], calculate: ({ x1, x2, x3, x4 }) => (Number(x1) + Number(x2) + Number(x3) + Number(x4)) / 4, resultLabel: "Mean", resultUnit: "" },
  { id: 39, name: "Percentage Change", symbol: "%Δ = (new−old)/old × 100", category: "Statistics", description: "Measure relative increase or decrease between two values.", variables: [{ key: "old", label: "Original value", unit: "" }, { key: "newValue", label: "New value", unit: "" }], calculate: ({ old, newValue }) => Number(old) === 0 ? null : (Number(newValue) - Number(old)) / Number(old) * 100, resultLabel: "Percentage change", resultUnit: "%" },
  { id: 40, name: "Compound Interest", symbol: "A = P(1 + r/n)ⁿᵗ", category: "Finance", description: "Calculate balance with periodic compound interest.", variables: [{ key: "p", label: "Principal P", unit: "$" }, { key: "r", label: "Annual rate", unit: "%" }, { key: "n", label: "Compounds/year", unit: "" }, { key: "t", label: "Time", unit: "years" }], calculate: ({ p, r, n, t }) => Number(p) * (1 + Number(r) / 100 / Number(n)) ** (Number(n) * Number(t)), resultLabel: "Future value", resultUnit: "$" },
  { id: 41, name: "Simple Interest", symbol: "I = Prt", category: "Finance", description: "Calculate interest earned without compounding.", variables: [{ key: "p", label: "Principal P", unit: "$" }, { key: "r", label: "Annual rate", unit: "%" }, { key: "t", label: "Time", unit: "years" }], calculate: ({ p, r, t }) => Number(p) * Number(r) / 100 * Number(t), resultLabel: "Interest", resultUnit: "$" },
  { id: 42, name: "Future Value", symbol: "FV = PV(1+r)ᵗ", category: "Finance", description: "Project a present value forward using an annual growth rate.", variables: [{ key: "pv", label: "Present value", unit: "$" }, { key: "r", label: "Growth rate", unit: "%" }, { key: "t", label: "Time", unit: "years" }], calculate: ({ pv, r, t }) => Number(pv) * (1 + Number(r) / 100) ** Number(t), resultLabel: "Future value", resultUnit: "$" },
  { id: 43, name: "Celsius to Fahrenheit", symbol: "°F = (°C × 9/5) + 32", category: "Math", description: "Convert a temperature from Celsius to Fahrenheit.", variables: [{ key: "c", label: "Celsius", unit: "°C" }], calculate: ({ c }) => Number(c) * 9 / 5 + 32, resultLabel: "Fahrenheit", resultUnit: "°F" },
  { id: 44, name: "Degrees to Radians", symbol: "rad = degrees × π/180", category: "Math", description: "Convert an angle from degrees to radians.", variables: [{ key: "degrees", label: "Degrees", unit: "°" }], calculate: ({ degrees }) => Number(degrees) * Math.PI / 180, resultLabel: "Radians", resultUnit: "rad" },
  { id: 45, name: "Pythagorean Trigonometric Identity", symbol: "sin²θ + cos²θ = 1", category: "Math", description: "Verify the fundamental identity for sine and cosine.", variables: [{ key: "sin", label: "sin θ", unit: "" }, { key: "cos", label: "cos θ", unit: "" }], calculate: ({ sin, cos }) => Number(sin) ** 2 + Number(cos) ** 2, resultLabel: "Identity result", resultUnit: "" },
  { id: 46, name: "Law of Sines", symbol: "a/sin A = b/sin B", category: "Math", description: "Find side a using one known side and two angles.", variables: [{ key: "b", label: "Side b", unit: "" }, { key: "aAngle", label: "Angle A", unit: "deg" }, { key: "bAngle", label: "Angle B", unit: "deg" }], calculate: ({ b, aAngle, bAngle }) => Number(Math.sin(Number(bAngle) * Math.PI / 180)) === 0 ? null : Number(b) * Math.sin(Number(aAngle) * Math.PI / 180) / Math.sin(Number(bAngle) * Math.PI / 180), resultLabel: "Side a", resultUnit: "" },
  { id: 47, name: "Law of Cosines", symbol: "c = √(a²+b²−2ab cos C)", category: "Math", description: "Find a triangle side from two sides and the included angle.", variables: [{ key: "a", label: "Side a", unit: "" }, { key: "b", label: "Side b", unit: "" }, { key: "angle", label: "Angle C", unit: "deg" }], calculate: ({ a, b, angle }) => Math.sqrt(Number(a) ** 2 + Number(b) ** 2 - 2 * Number(a) * Number(b) * Math.cos(Number(angle) * Math.PI / 180)), resultLabel: "Side c", resultUnit: "" },
  { id: 48, name: "Line Equation", symbol: "y = mx + b", category: "Math", description: "Find the y-coordinate on a straight line.", variables: [{ key: "m", label: "Slope m", unit: "" }, { key: "x", label: "x", unit: "" }, { key: "b", label: "Intercept b", unit: "" }], calculate: ({ m, x, b }) => Number(m) * Number(x) + Number(b), resultLabel: "y-coordinate", resultUnit: "" },
  { id: 49, name: "Cylinder Volume", symbol: "V = πr²h", category: "Math", description: "Calculate the volume of a cylinder.", variables: [{ key: "r", label: "Radius", unit: "m" }, { key: "h", label: "Height", unit: "m" }], calculate: ({ r, h }) => Math.PI * Number(r) ** 2 * Number(h), resultLabel: "Volume", resultUnit: "m³" },
  { id: 50, name: "Cone Volume", symbol: "V = ⅓πr²h", category: "Math", description: "Calculate the volume of a cone.", variables: [{ key: "r", label: "Radius", unit: "m" }, { key: "h", label: "Height", unit: "m" }], calculate: ({ r, h }) => Math.PI * Number(r) ** 2 * Number(h) / 3, resultLabel: "Volume", resultUnit: "m³" },
  { id: 51, name: "Kinematic Velocity", symbol: "v = u + at", category: "Physics", description: "Find final velocity under constant acceleration.", variables: [{ key: "u", label: "Initial velocity", unit: "m/s" }, { key: "a", label: "Acceleration", unit: "m/s²" }, { key: "t", label: "Time", unit: "s" }], calculate: ({ u, a, t }) => Number(u) + Number(a) * Number(t), resultLabel: "Final velocity", resultUnit: "m/s" },
  { id: 52, name: "Kinematic Displacement", symbol: "s = ut + ½at²", category: "Physics", description: "Find displacement under constant acceleration.", variables: [{ key: "u", label: "Initial velocity", unit: "m/s" }, { key: "a", label: "Acceleration", unit: "m/s²" }, { key: "t", label: "Time", unit: "s" }], calculate: ({ u, a, t }) => Number(u) * Number(t) + 0.5 * Number(a) * Number(t) ** 2, resultLabel: "Displacement", resultUnit: "m" },
  { id: 53, name: "Kinematic Speed-Distance", symbol: "v² = u² + 2as", category: "Physics", description: "Find final speed without using time.", variables: [{ key: "u", label: "Initial velocity", unit: "m/s" }, { key: "a", label: "Acceleration", unit: "m/s²" }, { key: "s", label: "Displacement", unit: "m" }], calculate: ({ u, a, s }) => Math.sqrt(Number(u) ** 2 + 2 * Number(a) * Number(s)), resultLabel: "Final speed", resultUnit: "m/s" },
  { id: 54, name: "Boyle's Law", symbol: "P₁V₁ = P₂V₂", category: "Chemistry", description: "Find pressure after a volume change at constant temperature.", variables: [{ key: "p1", label: "Initial pressure", unit: "Pa" }, { key: "v1", label: "Initial volume", unit: "m³" }, { key: "v2", label: "Final volume", unit: "m³" }], calculate: ({ p1, v1, v2 }) => Number(v2) === 0 ? null : Number(p1) * Number(v1) / Number(v2), resultLabel: "Final pressure", resultUnit: "Pa" },
  { id: 55, name: "Charles's Law", symbol: "V₁/T₁ = V₂/T₂", category: "Chemistry", description: "Find volume after a temperature change at constant pressure.", variables: [{ key: "v1", label: "Initial volume", unit: "m³" }, { key: "t1", label: "Initial temperature", unit: "K" }, { key: "t2", label: "Final temperature", unit: "K" }], calculate: ({ v1, t1, t2 }) => Number(t1) === 0 ? null : Number(v1) * Number(t2) / Number(t1), resultLabel: "Final volume", resultUnit: "m³" },
  { id: 56, name: "Gay-Lussac's Law", symbol: "P₁/T₁ = P₂/T₂", category: "Chemistry", description: "Find pressure after a temperature change at constant volume.", variables: [{ key: "p1", label: "Initial pressure", unit: "Pa" }, { key: "t1", label: "Initial temperature", unit: "K" }, { key: "t2", label: "Final temperature", unit: "K" }], calculate: ({ p1, t1, t2 }) => Number(t1) === 0 ? null : Number(p1) * Number(t2) / Number(t1), resultLabel: "Final pressure", resultUnit: "Pa" },
  { id: 57, name: "Henry's Law", symbol: "C = kH·P", category: "Chemistry", description: "Estimate dissolved gas concentration from its partial pressure.", variables: [{ key: "kh", label: "Henry constant", unit: "mol/(L·atm)" }, { key: "p", label: "Partial pressure", unit: "atm" }], calculate: ({ kh, p }) => Number(kh) * Number(p), resultLabel: "Dissolved concentration", resultUnit: "mol/L" },
  { id: 58, name: "Population Standard Deviation", symbol: "σ = √(Σ(x−μ)²/N)", category: "Statistics", description: "Calculate the population standard deviation of four values.", variables: [{ key: "x1", label: "Value 1", unit: "" }, { key: "x2", label: "Value 2", unit: "" }, { key: "x3", label: "Value 3", unit: "" }, { key: "x4", label: "Value 4", unit: "" }], calculate: ({ x1, x2, x3, x4 }) => { const data = [Number(x1), Number(x2), Number(x3), Number(x4)]; const mean = data.reduce((sum, value) => sum + value, 0) / data.length; return Math.sqrt(data.reduce((sum, value) => sum + (value - mean) ** 2, 0) / data.length) }, resultLabel: "Standard deviation", resultUnit: "" },
  { id: 59, name: "Pearson Correlation", symbol: "r = cov(X,Y)/(σxσy)", category: "Statistics", description: "Estimate the correlation from three paired observations.", variables: [{ key: "x1", label: "X₁", unit: "" }, { key: "y1", label: "Y₁", unit: "" }, { key: "x2", label: "X₂", unit: "" }, { key: "y2", label: "Y₂", unit: "" }, { key: "x3", label: "X₃", unit: "" }, { key: "y3", label: "Y₃", unit: "" }], calculate: ({ x1, y1, x2, y2, x3, y3 }) => { const xs = [Number(x1), Number(x2), Number(x3)]; const ys = [Number(y1), Number(y2), Number(y3)]; const xm = xs.reduce((a, b) => a + b, 0) / 3; const ym = ys.reduce((a, b) => a + b, 0) / 3; const numerator = xs.reduce((sum, x, i) => sum + (x - xm) * (ys[i] - ym), 0); const denominator = Math.sqrt(xs.reduce((sum, x) => sum + (x - xm) ** 2, 0) * ys.reduce((sum, y) => sum + (y - ym) ** 2, 0)); return denominator === 0 ? null : numerator / denominator }, resultLabel: "Correlation coefficient", resultUnit: "r" },
  { id: 60, name: "Present Value", symbol: "PV = FV/(1+r)ᵗ", category: "Finance", description: "Find today's value of a future cash flow.", variables: [{ key: "fv", label: "Future value", unit: "$" }, { key: "r", label: "Interest rate", unit: "%" }, { key: "t", label: "Time", unit: "years" }], calculate: ({ fv, r, t }) => Number(fv) / (1 + Number(r) / 100) ** Number(t), resultLabel: "Present value", resultUnit: "$" },
  { id: 61, name: "Profit Margin", symbol: "Margin = Profit/Revenue × 100", category: "Finance", description: "Measure profit as a percentage of revenue.", variables: [{ key: "profit", label: "Profit", unit: "$" }, { key: "revenue", label: "Revenue", unit: "$" }], calculate: ({ profit, revenue }) => Number(revenue) === 0 ? null : Number(profit) / Number(revenue) * 100, resultLabel: "Profit margin", resultUnit: "%" },
  { id: 62, name: "Profitability Ratio", symbol: "ROI = Profit/Cost × 100", category: "Finance", description: "Measure return relative to the original cost.", variables: [{ key: "profit", label: "Profit", unit: "$" }, { key: "cost", label: "Investment cost", unit: "$" }], calculate: ({ profit, cost }) => Number(cost) === 0 ? null : Number(profit) / Number(cost) * 100, resultLabel: "Profitability", resultUnit: "%" },
]


const categories = ['All', 'Math', 'Physics', 'Engineering', 'Chemistry', 'Statistics', 'Finance']
const icons = { Math: 'π', Physics: 'Φ', Engineering: 'Ω', Chemistry: '⚗', Statistics: 'σ', Finance: '$' }
const units = { m: { factors: { m: 1, cm: 100, ft: 3.28084, in: 39.3701 } }, kg: { factors: { kg: 1, g: 1000, lb: 2.20462 } }, s: { factors: { s: 1, min: 1 / 60, h: 1 / 3600 } } }
const diagramFor = (formula) => formula.id === 2 || formula.id === 3 ? 'circle' : formula.id === 4 ? 'triangle' : formula.id === 11 ? 'force' : null

function App() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('All')
  const [selectedId, setSelectedId] = useState(11)
  const [favorites, setFavorites] = useState([])
  const [values, setValues] = useState({})
  const [result, setResult] = useState(null)
  const [error, setError] = useState('')
  const [isDark, setIsDark] = useState(false)
  const [history, setHistory] = useState(() => JSON.parse(localStorage.getItem('formula-history') || '[]'))
  const [showHistory, setShowHistory] = useState(false)
  const [quiz, setQuiz] = useState(null)
  const [quizAnswer, setQuizAnswer] = useState('')
  const [quizMessage, setQuizMessage] = useState('')
  const [converter, setConverter] = useState({ amount: '', from: 'm', to: 'cm' })

  const filteredFormulas = useMemo(() => formulas.filter((formula) => {
    const searchable = `${formula.name} ${formula.description} ${formula.symbol} ${formula.category}`.toLowerCase()
    return (category === 'All' || formula.category === category) && searchable.includes(query.toLowerCase())
  }), [category, query])
  const selectedFormula = formulas.find((formula) => formula.id === selectedId) || formulas[0]
  const isFavorite = favorites.includes(selectedFormula.id)

  const selectFormula = (id) => { setSelectedId(id); setResult(null); setError(''); setValues({}) }
  const calculate = () => {
    setError('')
    if (!selectedFormula.variables.every(({ key }) => values[key] !== undefined && values[key] !== '')) { setError('Please fill in every field.'); return }
    const calculated = selectedFormula.calculate(values)
    if (calculated === null || Number.isNaN(calculated)) { setError('These values cannot produce a valid result.'); setResult(null); return }
    setResult(calculated)
    addHistory(selectedFormula, calculated)
  }
  const toggleFavorite = (id) => setFavorites((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const formattedResult = Array.isArray(result) ? result.map((item) => item.toFixed(3)).join('  or  ') : Number(result).toLocaleString('en-US', { maximumFractionDigits: 4 })
  const diagram = diagramFor(selectedFormula)
  const addHistory = (formula, calculated) => { const item = { id: Date.now(), formula: formula.name, symbol: formula.symbol, result: Array.isArray(calculated) ? calculated.join(' or ') : Number(calculated).toFixed(3), time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }; const next = [item, ...history].slice(0, 12); setHistory(next); localStorage.setItem('formula-history', JSON.stringify(next)) }
  const convertValue = converter.amount === '' ? '' : Number(converter.amount) * units[converter.from].factors[converter.to] / units[converter.from].factors[converter.from]
  const startQuiz = () => { const candidates = formulas.filter((item) => item.id !== 7); const item = candidates[Math.floor(Math.random() * candidates.length)]; const quizValues = Object.fromEntries(item.variables.map((variable, index) => [variable.key, String(index + 2)])); setQuiz({ formula: item, answer: item.calculate(quizValues), values: quizValues }); setQuizAnswer(''); setQuizMessage('') }

  return (
    <div className={isDark ? 'app dark' : 'app'}>
      <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">∑</span><span><strong>Formula</strong><em>Hub</em></span></a><nav className="nav-links"><a className="active" href="#library">Library</a><a href="#calculator">Calculator</a><a href="#tools">Tools</a><a href="#about">About</a></nav><div className="top-actions"><button className="history-button" onClick={() => setShowHistory((current) => !current)}>↺ <span>History</span></button><button className="theme-button" onClick={() => setIsDark((current) => !current)} aria-label="Toggle theme">{isDark ? '☀' : '◐'}</button></div></header>
      <main id="top">
        <section className="hero"><div className="hero-copy"><span className="eyebrow">Your intelligent science reference</span><h1>Every formula you need.<br /><span>One place.</span></h1><p>Explore essential formulas in mathematics, physics, engineering, chemistry, statistics, and finance. Understand them, then calculate your answer instantly.</p><div className="hero-stats"><span><b>{String(formulas.length).padStart(2, '0')}</b> formulas</span><span><b>06</b> disciplines</span><span><b>∞</b> ways to learn</span></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="formula-orb">π<br /><small>F = ma</small></div><span className="floating-chip chip-one">∫ f(x) dx</span><span className="floating-chip chip-two">Δ = b² − 4ac</span></div></section>
        <section className="workspace" id="library"><div className="section-heading"><div><span className="section-kicker">Explore and learn</span><h2>Formula library</h2></div><span className="count-badge">{filteredFormulas.length} formulas</span></div><div className="toolbar"><label className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search a formula, concept, or symbol..." aria-label="Search formulas" />{query && <button onClick={() => setQuery('')} aria-label="Clear search">×</button>}</label><div className="category-tabs">{categories.map((item) => <button key={item} className={category === item ? 'selected' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div></div>
          <div className="content-grid"><div className="formula-list">{filteredFormulas.length ? filteredFormulas.map((formula) => <button key={formula.id} className={`formula-card ${selectedFormula.id === formula.id ? 'active-card' : ''}`} onClick={() => selectFormula(formula.id)}><span className={`category-dot dot-${formula.category}`}>{icons[formula.category]}</span><span className="card-info"><strong>{formula.name}</strong><small>{formula.category}</small></span><span className="card-symbol">{formula.symbol}</span><span className="card-arrow">→</span></button>) : <div className="empty-state">No formulas found. Try another search.</div>}</div>
            <aside className="details-card" id="calculator"><div className="details-top"><span className={`category-dot large dot-${selectedFormula.category}`}>{icons[selectedFormula.category]}</span><div><span className="section-kicker">{selectedFormula.category}</span><h3>{selectedFormula.name}</h3></div><button className={`favorite ${isFavorite ? 'is-favorite' : ''}`} onClick={() => toggleFavorite(selectedFormula.id)} aria-label="Add to favorites">{isFavorite ? '★' : '☆'}</button></div><div className="formula-display">{selectedFormula.symbol}</div>{diagram && <div className={`formula-diagram ${diagram}`}>{diagram === 'circle' && <><span className="diagram-radius">r</span><div className="diagram-circle" /></>}{diagram === 'triangle' && <><span className="diagram-base">b</span><span className="diagram-height">h</span><div className="diagram-triangle" /></>}{diagram === 'force' && <><span className="force-arrow">F →</span><div className="diagram-block">m</div></>}</div>}<p className="formula-description">{selectedFormula.description}</p><div className="divider" /><h4>Calculate your result</h4><div className="inputs-grid">{selectedFormula.variables.map((variable) => <label key={variable.key}><span>{variable.label}</span><div className="input-wrap"><input type="number" value={values[variable.key] || ''} onChange={(event) => { const next = { ...values, [variable.key]: event.target.value }; setValues(next); setError(''); setResult(null); if (selectedFormula.variables.every(({ key }) => next[key] !== undefined && next[key] !== '')) { const live = selectedFormula.calculate(next); if (live !== null && !Number.isNaN(live)) setResult(live) } }} placeholder="0" /><small>{variable.unit}</small></div></label>)}</div><button className="calculate-button" onClick={calculate}>Calculate now <span>↗</span></button>{error && <p className="error-message">{error}</p>}{result !== null && <div className="result-box"><span>{selectedFormula.resultLabel}</span><strong>{formattedResult} {selectedFormula.resultUnit}</strong></div>}</aside></div></section>
        <section className="tools-section" id="tools"><div className="tool-card"><div><span className="section-kicker">Quick challenge</span><h2>Test your knowledge</h2><p>Get a random formula and enter the correct answer.</p></div><button className="tool-button" onClick={startQuiz}>Start quick quiz</button>{quiz && <div className="quiz-box"><strong>{quiz.formula.name}</strong><span>{quiz.formula.symbol}</span><small>Use these values: {quiz.formula.variables.map((v, index) => `${v.label} = ${index + 2}`).join(', ')}</small><div className="quiz-input"><input type="number" value={quizAnswer} onChange={(event) => setQuizAnswer(event.target.value)} placeholder="Your answer" /><button onClick={() => setQuizMessage(Math.abs(Number(quizAnswer) - quiz.answer) < 0.05 ? 'Correct! Great work.' : `Not quite — the answer is ${Number(quiz.answer).toFixed(2)}.`)}>Check</button></div><b className={quizMessage.startsWith('Correct') ? 'success-message' : 'error-message'}>{quizMessage}</b></div>}</div><div className="tool-card converter-card"><div><span className="section-kicker">Unit converter</span><h2>Convert units</h2><p>Switch between common length, mass, and time units.</p></div><div className="converter-row"><input type="number" value={converter.amount} onChange={(event) => setConverter({ ...converter, amount: event.target.value })} placeholder="Amount" /><select value={converter.from} onChange={(event) => setConverter({ ...converter, from: event.target.value, to: Object.keys(units[event.target.value].factors)[1] || Object.keys(units[event.target.value].factors)[0] })}>{Object.keys(units).map((unit) => <option key={unit} value={unit}>{unit}</option>)}</select><span>→</span><select value={converter.to} onChange={(event) => setConverter({ ...converter, to: event.target.value })}>{Object.keys(units[converter.from].factors).map((unit) => <option key={unit} value={unit}>{unit}</option>)}</select><strong>{convertValue === '' ? '—' : Number(convertValue).toFixed(4)}</strong></div></div></section>
        {showHistory && <section className="history-panel"><div className="section-heading"><div><span className="section-kicker">Your activity</span><h2>Calculation history</h2></div><button className="clear-history" onClick={() => { setHistory([]); localStorage.removeItem('formula-history') }}>Clear history</button></div>{history.length ? <div className="history-list">{history.map((item) => <div key={item.id}><span>{item.formula}<small>{item.symbol}</small></span><b>{item.result}</b><time>{item.time}</time></div>)}</div> : <p className="empty-history">Your recent calculations will appear here.</p>}</section>}
        <section className="about-section" id="about"><span className="section-kicker">Built for curious minds</span><h2>Understand the formula, not just the answer.</h2><p>FormulaHub helps you move from theory to practice with a clear reference and a simple calculator for every formula.</p></section>
      </main><footer><span>FormulaHub © 2026</span><span>Made for learning and discovery</span></footer>
    </div>
  )
}

export default App
