const names = {
  1: 'نظرية فيثاغورس', 2: 'مساحة الدائرة', 3: 'محيط الدائرة', 4: 'مساحة المثلث', 5: 'مساحة المستطيل', 6: 'حجم الكرة', 7: 'المعادلة التربيعية', 8: 'المسافة بين نقطتين', 9: 'ميل المستقيم', 10: 'التباديل', 11: 'قانون نيوتن الثاني', 12: 'الطاقة الحركية', 13: 'طاقة الوضع الجاذبية', 14: 'الزخم', 15: 'الكثافة', 16: 'الضغط', 17: 'الشغل', 18: 'قوة الجاذبية', 19: 'قانون كولوم', 20: 'سرعة الموجة', 21: 'قانون هوك', 22: 'قانون الغاز المثالي', 23: 'القدرة الكهربائية', 24: 'الشحنة الكهربائية', 25: 'قانون أوم', 26: 'المقاومة الكهربائية', 27: 'الإجهاد العمودي', 28: 'الانفعال العمودي', 29: 'معدل التدفق', 30: 'عدد رينولدز', 31: 'التمدد الحراري', 32: 'معامل الأمان', 33: 'المولارية', 34: 'الأس الهيدروجيني pH', 35: 'معادلة التخفيف', 36: 'النسبة المئوية الكتلية', 37: 'الدرجة المعيارية Z', 38: 'المتوسط الحسابي', 39: 'التغير النسبي', 40: 'الفائدة المركبة', 41: 'الفائدة البسيطة', 42: 'القيمة المستقبلية', 43: 'السيلسيوس إلى فهرنهايت', 44: 'الدرجات إلى راديان', 45: 'الهوية المثلثية لفيثاغورس', 46: 'قانون الجيوب', 47: 'قانون جيب التمام', 48: 'معادلة المستقيم', 49: 'حجم الأسطوانة', 50: 'حجم المخروط', 51: 'السرعة الحركية', 52: 'الإزاحة الحركية', 53: 'معادلة السرعة والمسافة', 54: 'قانون بويل', 55: 'قانون شارل', 56: 'قانون غاي-لوساك', 57: 'قانون هنري', 58: 'الانحراف المعياري للمجتمع', 59: 'معامل ارتباط بيرسون', 60: 'القيمة الحالية', 61: 'هامش الربح', 62: 'نسبة الربحية', 63: 'مجموع المتتالية الحسابية', 64: 'مجموع المتتالية الهندسية', 65: 'التوافيق', 66: 'تغيير أساس اللوغاريتم', 67: 'مساحة المثلث بصيغة هيرون', 68: 'طول القوس', 69: 'مساحة القطاع الدائري', 70: 'مقدار المتجه', 71: 'الضرب القياسي', 72: 'المسافة المقطوعة', 73: 'الدفع', 74: 'الزخم الزاوي', 75: 'العزم', 76: 'طاقة الوضع المرنة', 77: 'القدرة', 78: 'سرعة السقوط الحر', 79: 'الطاقة الحرارية', 80: 'معادلة العدسة', 81: 'إجهاد الانحناء', 82: 'انحراف الكمرة', 83: 'الضغط الهيدروستاتيكي', 84: 'التوصيل الحراري', 85: 'معامل القدرة', 86: 'معادلة الاستمرارية للتدفق', 87: 'الكفاءة', 88: 'الكسر المولي', 89: 'المولالية', 90: 'كثافة الغاز', 91: 'معادلة أرينيوس', 92: 'نصف عمر التفاعل من الرتبة الأولى', 93: 'التباين', 94: 'الخطأ المعياري', 95: 'المتوسط المرجح', 96: 'احتمال ثنائي الحدين', 97: 'صافي القيمة الحالية', 98: 'نقطة التعادل', 99: 'العائد السنوي', 100: 'نسبة الدين إلى حقوق الملكية',
}
const variableLabels = {
  a: 'المعامل a', b: 'المعامل b', c: 'المعامل c', r: 'نصف القطر', h: 'الارتفاع', l: 'الطول', w: 'العرض', m: 'الكتلة', v: 'السرعة', g: 'الجاذبية', f: 'القوة', d: 'المسافة', theta: 'الزاوية', t: 'الزمن', p: 'الضغط', i: 'التيار', rho: 'الكثافة', alpha: 'معامل التمدد', dt: 'التغير في الحرارة', u: 'السرعة الابتدائية', x: 'القيمة x', y: 'القيمة y', n: 'العدد n', q: 'الشحنة', lambda: 'الطول الموجي', cost: 'التكلفة', profit: 'الربح', revenue: 'الإيراد', fv: 'القيمة المستقبلية', pv: 'القيمة الحالية', rate: 'معدل الخصم', investment: 'الاستثمار الأولي', fixed: 'التكاليف الثابتة', price: 'السعر للوحدة', variable: 'التكلفة المتغيرة', output: 'المخرجات المفيدة', input: 'المدخلات', debt: 'إجمالي الدين', equity: 'حقوق الملكية', do: 'مسافة الجسم', di: 'مسافة الصورة', e: 'معامل يونغ', i1: 'العزم الأول', i2: 'العزم الثاني', s: 'الانحراف المعياري', p1: 'الضغط الأول', v1: 'الحجم أو السرعة الأولى', v2: 'الحجم أو السرعة الثانية', t1: 'درجة الحرارة الأولى', t2: 'درجة الحرارة الثانية', kh: 'ثابت هنري', ni: 'مولات المكوّن', nt: 'إجمالي المولات', mass: 'كتلة المذيب', total: 'العائد الكلي', first: 'الحد الأول', last: 'الحد الأخير', omega: 'السرعة الزاوية', k: 'الثابت k', power: 'القدرة', strength: 'المقاومة', stress: 'الإجهاد', area: 'المساحة', a1: 'المساحة الأولى', a2: 'المساحة الثانية', cashflow: 'التدفق النقدي', ax: 'مركبة aₓ', ay: 'مركبة aᵧ', bx: 'مركبة bₓ', by: 'مركبة bᵧ', w1: 'الوزن الأول', w2: 'الوزن الثاني', probability: 'الاحتمال',
}
const frenchNames = {
  1: 'Théorème de Pythagore', 2: 'Aire du cercle', 3: 'Circonférence du cercle', 4: 'Aire du triangle', 5: 'Aire du rectangle', 6: 'Volume de la sphère', 7: 'Équation quadratique', 8: 'Distance entre deux points', 9: 'Pente d’une droite', 10: 'Permutations', 11: 'Deuxième loi de Newton', 12: 'Énergie cinétique', 13: 'Énergie potentielle gravitationnelle', 14: 'Quantité de mouvement', 15: 'Masse volumique', 16: 'Pression', 17: 'Travail', 18: 'Force gravitationnelle', 19: 'Loi de Coulomb', 20: 'Vitesse d’onde', 21: 'Loi de Hooke', 22: 'Loi des gaz parfaits', 23: 'Puissance électrique', 24: 'Charge électrique', 25: 'Loi d’Ohm', 26: 'Résistance électrique', 27: 'Contrainte normale', 28: 'Déformation normale', 29: 'Débit', 30: 'Nombre de Reynolds', 31: 'Dilatation thermique', 32: 'Coefficient de sécurité', 33: 'Molarité', 34: 'pH', 35: 'Équation de dilution', 36: 'Pourcentage massique', 37: 'Score Z', 38: 'Moyenne arithmétique', 39: 'Variation en pourcentage', 40: 'Intérêt composé', 41: 'Intérêt simple', 42: 'Valeur future', 43: 'Celsius vers Fahrenheit', 44: 'Degrés vers radians', 45: 'Identité trigonométrique de Pythagore', 46: 'Loi des sinus', 47: 'Loi des cosinus', 48: 'Équation d’une droite', 49: 'Volume du cylindre', 50: 'Volume du cône', 51: 'Vitesse cinématique', 52: 'Déplacement cinématique', 53: 'Relation vitesse-distance', 54: 'Loi de Boyle', 55: 'Loi de Charles', 56: 'Loi de Gay-Lussac', 57: 'Loi de Henry', 58: 'Écart-type de la population', 59: 'Corrélation de Pearson', 60: 'Valeur actuelle', 61: 'Marge bénéficiaire', 62: 'Ratio de rentabilité', 63: 'Somme d’une suite arithmétique', 64: 'Somme d’une suite géométrique', 65: 'Combinaisons', 66: 'Changement de base logarithmique', 67: 'Aire du triangle de Héron', 68: 'Longueur d’arc', 69: 'Aire d’un secteur', 70: 'Norme d’un vecteur', 71: 'Produit scalaire', 72: 'Distance parcourue', 73: 'Impulsion', 74: 'Moment cinétique', 75: 'Couple', 76: 'Énergie potentielle élastique', 77: 'Puissance', 78: 'Vitesse de chute libre', 79: 'Énergie thermique', 80: 'Équation des lentilles', 81: 'Contrainte de flexion', 82: 'Déflexion d’une poutre', 83: 'Pression hydrostatique', 84: 'Conduction thermique', 85: 'Facteur de puissance', 86: 'Équation de continuité', 87: 'Rendement', 88: 'Fraction molaire', 89: 'Molalité', 90: 'Masse volumique d’un gaz', 91: 'Équation d’Arrhenius', 92: 'Demi-vie du premier ordre', 93: 'Variance', 94: 'Erreur standard', 95: 'Moyenne pondérée', 96: 'Probabilité binomiale', 97: 'Valeur actuelle nette', 98: 'Seuil de rentabilité', 99: 'Rendement annualisé', 100: 'Ratio dette/fonds propres',
}
const resultLabels = { Area: 'المساحة', Circumference: 'المحيط', Volume: 'الحجم', Roots: 'الجذور', Distance: 'المسافة', Slope: 'الميل', Force: 'القوة', Energy: 'الطاقة', Momentum: 'الزخم', Density: 'الكثافة', Pressure: 'الضغط', Work: 'الشغل', Power: 'القدرة', Efficiency: 'الكفاءة', Probability: 'الاحتمال', 'Net present value': 'صافي القيمة الحالية' }
const difficultyLabels = { Beginner: 'مبتدئ', Intermediate: 'متوسط', Advanced: 'متقدم' }
const relatedNames = { 'Kinetic Energy': 'الطاقة الحركية', Momentum: 'الزخم', Work: 'الشغل', "Newton's Second Law": 'قانون نيوتن الثاني', 'Molarity': 'المولارية', 'Dilution Equation': 'معادلة التخفيف', 'Arithmetic Mean': 'المتوسط الحسابي', 'Population Standard Deviation': 'الانحراف المعياري للمجتمع', 'Profit Margin': 'هامش الربح', 'Future Value': 'القيمة المستقبلية' }
const sourceNames = { 'Newtonian mechanics': 'الميكانيكا النيوتونية', 'Classical mechanics': 'الميكانيكا الكلاسيكية', 'General chemistry': 'الكيمياء العامة', 'Descriptive statistics': 'الإحصاء الوصفي', 'Introductory finance': 'مبادئ المالية', 'Standard introductory science relationship': 'علاقة علمية تمهيدية موثوقة' }
const detailOverrides = {
  11: { meaning: 'القوة المحصلة تساوي حاصل ضرب الكتلة في التسارع.', assumptions: 'يُفترض أن التسارع ناتج عن القوة المحصلة المؤثرة في الجسم.', example: 'عند m = 5 kg وa = 3 m/s² تكون F = 15 N.' },
  12: { meaning: 'الطاقة الحركية هي الطاقة التي يمتلكها الجسم بسبب حركته.', assumptions: 'تُقاس الكتلة بالكيلوغرام والسرعة بالمتر لكل ثانية.', example: 'عند m = 2 kg وv = 4 m/s تكون الطاقة 16 J.' },
  34: { meaning: 'يقيس الأس الهيدروجيني درجة حموضة المحلول على مقياس لوغاريتمي.', assumptions: 'يجب أن يكون تركيز أيونات الهيدروجين موجبًا ويُقاس بالمول لكل لتر.', example: 'عند [H⁺] = 0.001 mol/L تكون قيمة pH مساوية لـ3.' },
  59: { meaning: 'يقيس ارتباط بيرسون قوة واتجاه العلاقة الخطية بين متغيرين.', assumptions: 'يجب أن يملك كل من المتغيرين تباينًا غير صفري.', example: 'استخدم ثلاث أزواج من قيم X وY لتقدير معامل الارتباط r.' },
  62: { meaning: 'تقارن نسبة العائد على الاستثمار الربح بالتكلفة الأصلية للاستثمار.', assumptions: 'يجب أن تكون تكلفة الاستثمار موجبة وأن يستخدم الربح والتكلفة العملة نفسها.', example: 'عند ربح قدره 200 وتكلفة قدرها 1000 تكون النسبة 20%.' },
}

export function localizeFormula(formula, language) {
  if (language === 'en') return formula
  const isFrench = language === 'fr'
  const localizedNames = isFrench ? frenchNames : names
  const localizedName = localizedNames[formula.id] || formula.name
  const details = detailOverrides[formula.id] || {}
  const source = typeof formula.source === 'object' ? { ...formula.source, rationale: isFrench ? 'Cette référence présente la relation scientifique utilisée par cette formule.' : 'يقدم هذا المرجع العلاقة العلمية المستخدمة في هذا القانون.' } : (isFrench ? 'Référence scientifique introductive fiable' : (sourceNames[formula.source] || 'مرجع علمي تمهيدي موثوق'))
  const localizedDetails = isFrench ? { meaning: `Cette formule décrit la relation mathématique ou scientifique associée à ${localizedName}.`, assumptions: 'Les valeurs utilisent les unités indiquées et les conditions idéales habituelles sont supposées.', example: `Saisissez des valeurs positives pour calculer ${localizedName}.` } : { meaning: details.meaning || `يوضح هذا القانون العلاقة الرياضية أو العلمية المرتبطة بـ${localizedName}.`, assumptions: details.assumptions || 'تُستخدم القيم بالوحدات الموضحة وتُفترض الظروف المثالية المعتادة لهذا القانون.', example: details.example || `أدخل قيمًا موجبة في الحقول للحصول على نتيجة ${localizedName}.` }
  const localDifficulty = isFrench ? { Beginner: 'Débutant', Intermediate: 'Intermédiaire', Advanced: 'Avancé' }[formula.difficulty] : difficultyLabels[formula.difficulty]
  return { ...formula, name: localizedName, description: isFrench ? `Calculez ${localizedName} à partir des valeurs et unités indiquées.` : `احسب ${localizedName} باستخدام القيم والوحدات الموضحة.`, ...localizedDetails, difficulty: localDifficulty || formula.difficulty, relatedFormulas: isFrench ? formula.relatedFormulas.map((related) => `Formule associée : ${related}`) : formula.relatedFormulas.map((related) => relatedNames[related] || names[formula.id] || related), source, resultLabel: resultLabels[formula.resultLabel] || formula.resultLabel, variables: formula.variables.map((variable) => ({ ...variable, label: isFrench ? `Paramètre ${variable.label}` : (variableLabels[variable.key] || `المتغير ${variable.label}`) })) }
}
