import { useEffect, useMemo, useState } from 'react'

const translations = {
  en: {
    language: 'Language', english: 'English', arabic: 'العربية', history: 'History', library: 'Library', calculator: 'Calculator', tools: 'Tools', about: 'About',
    heroEyebrow: 'Your intelligent science reference', heroTitle: 'Every formula you need.', heroTitleAccent: 'One place.', heroDescription: 'Explore essential formulas in mathematics, physics, engineering, chemistry, statistics, and finance. Understand them, then calculate your answer instantly.', formulas: 'formulas', disciplines: 'disciplines', waysToLearn: 'ways to learn', explore: 'Explore and learn', formulaLibrary: 'Formula library', search: 'Search a formula, concept, or symbol...', searchLabel: 'Search formulas', clearSearch: 'Clear search', noResults: 'No formulas found. Try another search.', all: 'All',
    meaning: 'Meaning', assumptions: 'Assumptions', example: 'Example', difficulty: 'Difficulty', related: 'Related formulas', source: 'Source', sourceNotVerified: 'Academic source: Not yet verified', directSource: 'Direct source', supportingSource: 'Supporting source', calculateResult: 'Calculate your result', calculate: 'Calculate now', fillFields: 'Please fill in every field.', invalidResult: 'These values cannot produce a valid result.', removeFavorite: 'Remove from favorites', addFavorite: 'Add to favorites', toggleTheme: 'Toggle theme',
    quickChallenge: 'Quick challenge', testKnowledge: 'Test your knowledge', quizDescription: 'Get a random formula and enter the correct answer.', startQuiz: 'Start quick quiz', useValues: 'Use these values', yourAnswer: 'Your answer', check: 'Check', correct: 'Correct! Great work.', notQuite: (answer) => `Not quite — the answer is ${answer}.`, unitConverter: 'Unit converter', convertUnits: 'Convert units', converterDescription: 'Switch between length, mass, time, temperature, and pressure units.', amount: 'Amount', convertFrom: 'Convert from', convertTo: 'Convert to', activity: 'Your activity', calculationHistory: 'Calculation history', clearHistory: 'Clear history', emptyHistory: 'Your recent calculations will appear here.',
    builtFor: 'Built for curious minds', understand: 'Understand the formula, not just the answer.', aboutText: 'FormulaHub helps you move from theory to practice with a clear reference and a simple calculator for every formula.', madeFor: 'Made for learning and discovery', category: (value) => value,
  },
  fr: {
    language: 'Langue', english: 'English', arabic: 'العربية', history: 'Historique', library: 'Bibliothèque', calculator: 'Calculatrice', tools: 'Outils', about: 'À propos',
    heroEyebrow: 'Votre référence scientifique intelligente', heroTitle: 'Toutes les formules dont vous avez besoin.', heroTitleAccent: 'En un seul endroit.', heroDescription: 'Explorez les formules essentielles en mathématiques, physique, ingénierie, chimie, statistiques et finance. Comprenez-les, puis calculez votre résultat instantanément.', formulas: 'formules', disciplines: 'disciplines', waysToLearn: 'façons d’apprendre', explore: 'Explorez et apprenez', formulaLibrary: 'Bibliothèque de formules', search: 'Rechercher une formule, un concept ou un symbole...', searchLabel: 'Rechercher des formules', clearSearch: 'Effacer la recherche', noResults: 'Aucune formule trouvée. Essayez une autre recherche.', all: 'Toutes',
    meaning: 'Signification', assumptions: 'Hypothèses', example: 'Exemple', difficulty: 'Niveau', related: 'Formules associées', source: 'Source', sourceNotVerified: 'Source académique : pas encore vérifiée', directSource: 'Source directe', supportingSource: 'Source complémentaire', calculateResult: 'Calculez votre résultat', calculate: 'Calculer maintenant', fillFields: 'Veuillez remplir tous les champs.', invalidResult: 'Ces valeurs ne permettent pas d’obtenir un résultat valide.', removeFavorite: 'Retirer des favoris', addFavorite: 'Ajouter aux favoris', toggleTheme: 'Changer de thème',
    quickChallenge: 'Défi rapide', testKnowledge: 'Testez vos connaissances', quizDescription: 'Obtenez une formule aléatoire et saisissez la bonne réponse.', startQuiz: 'Commencer le quiz', useValues: 'Utilisez ces valeurs', yourAnswer: 'Votre réponse', check: 'Vérifier', correct: 'Correct ! Excellent travail.', notQuite: (answer) => `Pas tout à fait — la réponse est ${answer}.`, unitConverter: 'Convertisseur d’unités', convertUnits: 'Convertir des unités', converterDescription: 'Convertissez des unités de longueur, masse, temps, température et pression.', amount: 'Valeur', convertFrom: 'De', convertTo: 'Vers', activity: 'Votre activité', calculationHistory: 'Historique des calculs', clearHistory: 'Effacer l’historique', emptyHistory: 'Vos calculs récents apparaîtront ici.',
    builtFor: 'Conçu pour les esprits curieux', understand: 'Comprenez la formule, pas seulement la réponse.', aboutText: 'FormulaHub vous aide à passer de la théorie à la pratique grâce à une référence claire et une calculatrice simple pour chaque formule.', madeFor: 'Créé pour apprendre et découvrir', category: (value) => ({ Math: 'Mathématiques', Physics: 'Physique', Engineering: 'Ingénierie', Chemistry: 'Chimie', Statistics: 'Statistiques', Finance: 'Finance' }[value] || value),
  },
  ar: {
    language: 'اللغة', english: 'English', arabic: 'العربية', history: 'السجل', library: 'المكتبة', calculator: 'الحاسبة', tools: 'الأدوات', about: 'عن المشروع',
    heroEyebrow: 'مرجعك العلمي الذكي', heroTitle: 'كل القوانين التي تحتاجها.', heroTitleAccent: 'في مكان واحد.', heroDescription: 'استكشف أهم القوانين في الرياضيات والفيزياء والهندسة والكيمياء والإحصاء والمالية. افهم القانون ثم احسب النتيجة فورًا.', formulas: 'قانون', disciplines: 'مجالات', waysToLearn: 'طرق للتعلم', explore: 'استكشف وتعلّم', formulaLibrary: 'مكتبة القوانين', search: 'ابحث عن قانون أو مفهوم أو رمز...', searchLabel: 'البحث في القوانين', clearSearch: 'مسح البحث', noResults: 'لم يتم العثور على قوانين. جرّب بحثًا آخر.', all: 'الكل',
    meaning: 'المعنى', assumptions: 'الافتراضات', example: 'مثال', difficulty: 'المستوى', related: 'قوانين مرتبطة', source: 'المصدر', sourceNotVerified: 'المصدر الأكاديمي: لم يتم التحقق منه بعد', directSource: 'مصدر مباشر', supportingSource: 'مصدر مساند', calculateResult: 'احسب النتيجة', calculate: 'احسب الآن', fillFields: 'يرجى ملء جميع الحقول.', invalidResult: 'لا يمكن لهذه القيم إنتاج نتيجة صالحة.', removeFavorite: 'إزالة من المفضلة', addFavorite: 'إضافة إلى المفضلة', toggleTheme: 'تبديل المظهر',
    quickChallenge: 'تحدٍ سريع', testKnowledge: 'اختبر معلوماتك', quizDescription: 'احصل على قانون عشوائي وأدخل الإجابة الصحيحة.', startQuiz: 'ابدأ الاختبار السريع', useValues: 'استخدم هذه القيم', yourAnswer: 'إجابتك', check: 'تحقق', correct: 'صحيح! أحسنت.', notQuite: (answer) => `ليست الإجابة الصحيحة — الإجابة هي ${answer}.`, unitConverter: 'محول الوحدات', convertUnits: 'تحويل الوحدات', converterDescription: 'حوّل بين وحدات الطول والكتلة والزمن ودرجة الحرارة والضغط.', amount: 'القيمة', convertFrom: 'من', convertTo: 'إلى', activity: 'نشاطك', calculationHistory: 'سجل الحسابات', clearHistory: 'مسح السجل', emptyHistory: 'ستظهر حساباتك الأخيرة هنا.',
    builtFor: 'صُمم للعقول الفضولية', understand: 'افهم القانون، لا تكتفِ بالنتيجة.', aboutText: 'يساعدك FormulaHub على الانتقال من النظرية إلى التطبيق عبر مرجع واضح وحاسبة بسيطة لكل قانون.', madeFor: 'صُنع للتعلم والاكتشاف', category: (value) => ({ Math: 'رياضيات', Physics: 'فيزياء', Engineering: 'هندسة', Chemistry: 'كيمياء', Statistics: 'إحصاء', Finance: 'مالية' }[value] || value),
  },
}

export function useLanguage() {
  const [language, setLanguage] = useState(() => localStorage.getItem('formulahub-language') || 'en')
  const t = useMemo(() => translations[language], [language])
  useEffect(() => {
    localStorage.setItem('formulahub-language', language)
    document.documentElement.lang = language
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
  }, [language])
  return { language, setLanguage, t }
}
